🚧 Update to SDK 26.1.100
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🙆🏿‍♂️♝✵⚔️

Full error log:
Error:  asset 2022-7-25--0-29-38--0107250f-b829-431c-bdaf-b9eb79774939/main.min.js 293 KiB [emitted] (name: main) 1 related asset
runtime modules 57 bytes 1 module
asset modules 1.39 KiB
modules by path ./assets/tray/categories/*.svg 798 bytes 19 modules
modules by path ./assets/tray/park/*.svg 588 bytes 14 modules
./assets/icons/hejny.svg 42 bytes [built] [code generated]
javascript modules 262 KiB
modules by path ./src/tray/items/*.tsx 119 KiB 22 modules
modules by path ./src/tray/*.tsx 16 KiB 4 modules
modules by path ./node_modules/ 127 KiB
modules by path ./node_modules/react/ 70.6 KiB 2 modules
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 54.7 KiB [built] [code generated]
./node_modules/object-assign/index.js 2.06 KiB [built] [code generated]
./package.json 713 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx
45:51-64
[tsl] ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx(45,52)
TS2540: Cannot assign to 'notifications' because it is a read-only property.

ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx
45:100-106
[tsl] ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx(45,101)
TS2339: Property 'filter' does not exist on type 'BehaviorSubject<INotification[]>'.

ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx
46:37-49
[tsl] ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx(46,38)
TS7006: Parameter 'notification' implicitly has an 'any' type.

ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx
67:32-45
[tsl] ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx(67,33)
TS2540: Cannot assign to 'notifications' because it is a read-only property.

ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx
67:86-92
[tsl] ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx(67,87)
TS2339: Property 'filter' does not exist on type 'BehaviorSubject<INotification[]>'.

ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx
68:13-25
[tsl] ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\makeDepracatedWarningModule.tsx(68,14)
TS7006: Parameter 'notification' implicitly has an 'any' type.

webpack 5.35.1 compiled with 6 errors in 7677 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\webpack\lib\Watching.js:201:28)