🚧 Update to SDK 27.36.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🧒🏼👦🏼🛌🏿👨🏽‍🦼

Full error log:
Error:  asset 2022-9-14--22-41-28--a665e17a-0ff4-4abe-869a-3f3bd4b58379/main.min.js 324 KiB [emitted] (name: main) 1 related asset
runtime modules 57 bytes 1 module
asset modules 1.39 KiB
modules by path ./assets/tray/categories/*.svg 798 bytes 19 modules
modules by path ./assets/tray/park/*.svg 588 bytes 14 modules
./assets/icons/hejny.svg 42 bytes [built] [code generated]
javascript modules 293 KiB
modules by path ./src/tray/items/*.tsx 119 KiB 22 modules
modules by path ./src/tray/*.tsx 16 KiB 4 modules
modules by path ./node_modules/ 158 KiB
modules by path ./node_modules/react/ 70.6 KiB 2 modules
./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 85.4 KiB [built] [code generated]
./node_modules/object-assign/index.js 2.06 KiB [built] [code generated]
./package.json 712 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\HeduDeprecatedModule.tsx
39:6-23
[tsl] ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\HeduDeprecatedModule.tsx(39,7)
TS2515: Non-abstract class 'HeduDeprecatedArt' does not implement inherited abstract member 'bottomRight' from class 'Abstract2dArt'.

ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\HeduDeprecatedModule.tsx
39:6-23
[tsl] ERROR in C:\Users\me\work\collboard\hedu-collboard-integration\src\tray\HeduDeprecatedModule.tsx(39,7)
TS2515: Non-abstract class 'HeduDeprecatedArt' does not implement inherited abstract member 'topLeft' from class 'Abstract2dArt'.

webpack 5.35.1 compiled with 2 errors in 7323 ms

Error:
at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
at Generator.next (<anonymous>)
at C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
at new Promise (<anonymous>)
at __awaiter (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
at Watching.handler (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
at C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\webpack\lib\Watching.js:204:9
at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
at Watching._done (C:\Users\me\work\collboard\hedu-collboard-integration\node_modules\webpack\lib\Watching.js:201:28)